language: node_js
node_js: '8'
cache:
  yarn: true
  directories:
      - node_modules

dist: trusty

git:
  depth: 5

addons:
  chrome: stable

script:
  - npm run build:debug
  - npm run serve
  - sleep 3
  - npm run test
